spring.application.name=cursos
spring.datasource.url=jdbc:mysql://localhost:3306/cursos?createDatabaseIfNotExist=true
spring.datasource.username=marcos
spring.datasource.password=marcos123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql= false
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect